### ISSUE TITLE
fdr values

### ISSUE THREAD

**Issue by alejandro-jimenezsanchez** [BioNinja/GSEApy#33]
Hi,

This is more like a questions than an issue, hope it's OK.

My questions is about ssGSEA FDR calculation:

If you have say 50 gene sets, assuming in reality all  of those gene sets are actually "enriched", does the FDR calculation will by default output some non-significant (q > 0.05) values, or would all the gene sets have a significant value (q < 0.05)? Again assuming all the genes in those gene sets are highly expressed for example.

Thanks

**Comment by BioNinja** [comment]
Yes, @alejandro-jimenezsanchez. However, GSEA use a false discovery rate (FDR) of 0.25 rather than the more classic 0.05 as significant cut-off. In short, FDR method for GSEA is different from classical fdr(e.g. ``p.adjust()`` in R)

Please, see here for details: http://www.broadinstitute.org/gsea/doc/GSEAUserGuideFrame.html?Interpreting_GSEA


FDR for ssGSEA module implemented in GSEApy use the same method with GSEA. But some other tools use the classic FDR.

I think you should use GSEApy-0.8.6, to get the most reliable fdrs. See Released notes for reasons. Thanks

**Comment by alejandro-jimenezsanchez** [comment]
Great thanks for the reply!

By the way, I'm trying to update gseapy through conda, but it's not updating it... and I don't see the latest version in bioconda, so I assume i should update it "manually" right?  Just wondering :)

**Comment by BioNinja** [comment]
please install it by:
    conda install gseapy -c bioninja

or, use pip
    pip install gseapy

**Comment by alejandro-jimenezsanchez** [comment]
THANKS!
